### ISSUE TITLE
Implementation of iconv is not correct?

### ISSUE THREAD

**Issue by ghost** [degobbis/docker-lamp#1]
See https://github.com/joomla/joomla-cms/issues/32344

**Comment by degobbis** [comment]
Thank you for bringing this to my attention. There seems to be a bug in the Alpine images, which serve as the basis for the PHP versions.

This has now been fixed in my images.

To use the new images please execute the following commands inside ob the docker-lamp basedir, the server must be shut down (make server-down):
- make update-images
- make delete-obsolete-images
- make server-up

Don't be disturbed by the fact that the phpinfo says 'iconv implemented: undefined'.
