### ISSUE TITLE
How do I change the location of the www directory?

### ISSUE THREAD

**Issue by pjdevries** [degobbis/docker-lamp#10]
Good morning Guido.

I would like to put the database and www directories in a location of my choosing, preferably outside the docker-lamp directory. With some minor modifications, I managed to do that for the database directory. I can not find how to do that for the www directory though. Can you give me some pointers?

**Comment by degobbis** [comment]
Hi,
since you are using the [2.0.0-dev Branch](https://github.com/degobbis/docker-lamp/tree/2.0.0-dev), you can use this solution:
Copy everything in the `./data` directory to the directory of your choice.
Change the value in the `.env` of `APP_BASEDIR` and enter the absolute path to the directory where you copied the files.
Start the server and everything should work.

You can also copy the `.env` there, then you have to change to this directory in the terminal and start the docker-lamp server from there using the absolute path.

Example:
The docker-lamp git clone is located in `/opt/git/docker-lamp`.
You copied everything from `/opt/git/docker-lamp/data` to `/home/$USER/html`.
Also in `/home/$USER/html` now comes the `.env`.
`APP_BASEDIR` would then be `APP_BASEDIR="/home/$USER/html"`.
Now change to `/home/$USER/html` with `cd /home/$USER/html` and execute the command `/opt/git/docker-lamp/docker-lamp start` from there.

**Comment by pjdevries** [comment]
Hi Guido,

Yes I'm using the [2.0.0-dev Branch](https://github.com/degobbis/docker-lamp/tree/2.0.0-dev). Apologies for not mentioning that explicitly in all my posts.

Although I was looking for relocation of individual sub directories of `./data`, this approach seems to be a useful alternative. The main advantage is separation of docker-lamp specific and none specific data, so I will definitely do that. However, I would still like to separate the `www` directory from the rest. Is there a way to achieve that as well?

**Comment by degobbis** [comment]
This would only be possible if you adjust all configuration files, because the path is always expected inside the container in `/srv/www`.

So all PHP yml, the Apache yml and all vHosts would have to be adjusted.

You can do this via overrides in `./data`, but side effects are not excluded.

Anyway, I would not recommend you to do that.

**Comment by pjdevries** [comment]
I already have my own separate branch in my forked repo, so I don't mind some additional customizing :) I'll look into it, to see if I can make it parameterizable, and if it becomes to messy and cumbersome, at least you explained me the alternative. Thanx for that.
