### ISSUE TITLE
Can macros be used for the automaticaly creation of vhosts for specific PHP versions?

### ISSUE THREAD

**Issue by pjdevries** [degobbis/docker-lamp#8]
Hi Guido. First I like to thank you for making this Docker setup available to the rest of the world. I've only just started experimenting with it, after struggling to get SSL certificates to work in my own environment. Fortunately @pe7er pointed me in this direction and I'm already starting to like it. Quite complex but also quite flexible. 

The `README.md` in folder  `.../data/httpd/apache24` states: 

> It's also possible to use the macros for the automatically creation of vhosts for all original PHP versions. 

This worked like a charm for my first experimental domain `try.obix.local`. The site was accessible both via `http` and `https` for all 4 activated PHP versions in the blink of an eye :) Enumeration of domain names in environment variables is somewhat inconvenient and unpractical, but it works and I can't think of a better solution at the moment.

And then my question. Is it possible to use that easy macro mechanism, to add Vhosts for one or several but not necessarily all PHP versions at once? Or can this only be done by crafting dedicated `.conf` files for such occasions?

**Comment by degobbis** [comment]
Hello pjdevries,

thank you for the compliment.

The easiest way to do this is:
- Copy the file [.config/httpd/apache24/vhosts/10-macro-extra-domains.conf](https://github.com/degobbis/docker-lamp/blob/2.0.0-dev/.config/httpd/apache24/vhosts/10-macro-extra-domains.conf) to [APP_BASEDIR/httpd/apache24](https://github.com/degobbis/docker-lamp/tree/2.0.0-dev/data/httpd/apache24) and rename it to e.g. `11-my-macro.conf`
- Delete lines 18 - 46 as they are not needed
- Rename the macro in line 10, e.g. from `VHost` to `MyVhost`.
- in line 11 - 15 you can then remove the entries that you do not need.
- Adjust the call in your other .conf from `Use VHost example.org ""` to `Use MyVhost example.org ""` and your wish will be fulfilled.

But basically it doesn't matter if the VHosts are created dynamically for all PHP versions, because only the PHP versions that are defined in the `.env` variable `PHP_TO_USE="php74 php80 php81"` can be called.

**Comment by pjdevries** [comment]
Thanx for the swift response. This is quite easy to do indeed. Thanx for the detailed explanation.

> But basically it doesn't matter if the VHosts are created dynamically for all PHP versions, because only the PHP versions that are defined in the .env variable PHP_TO_USE="php74 php80 php81" can be called.

That's true. But in my current Docker environment, I have quite a few projects using various PHP versions. As long as there is a need for that much versions, I like to be able to switch effortless between various projects. Your setup makes that possible. On the other hand, I prefer not to access sites with a "wrong" PHP version by accident. Not having unneeded Vhosts, prevents me from doing so :)

**Comment by degobbis** [comment]
I am not quite sure, is this issue resolved?

**Comment by pjdevries** [comment]
I'm not quite sure either :D

I started all over again and threw away all custom stuff, including the `10-macro-extra-domains.conf` override. The basic setup is working now. First get some work done and then look at this again. Until then, let's assume it's resolved.
